name: Build
on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    name: compile
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup SourcePawn Compiler
        id: setup-sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.12.x"

      - name: Compile plugin
        shell: bash
        run: |
          mkdir -p build
          spcomp \
            "scripting/fkz-api.sp" \
            -i "sm-ext-json/scripting/include" \
            -i "sm-ext-websocket/scripting/include" \
            -i "gokz/addons/sourcemod/scripting/include" \
            -i "$includePath" \
            -o "build/fkz-api.smx"

      - name: Stage release files
        run: |
          mkdir -p staging/addons/sourcemod/plugins
          mkdir -p staging/addons/sourcemod/configs
          mkdir -p staging/addons/sourcemod/scripting/include
          cp build/fkz-api.smx staging/addons/sourcemod/plugins/
          cp configs/fkz-api.cfg staging/addons/sourcemod/configs/
          cp scripting/include/fkz-api.inc staging/addons/sourcemod/scripting/include/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fkz-api
          path: staging/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: fkz-api
          path: release

      - name: Create archive
        run: cd release && tar -czf ../fkz-api.tar.gz .

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: fkz-api.tar.gz
